### ISSUE TITLE
The Deploy_EE section of release workflow fails

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ansible_collections_tooling#10]
# Summary

The Deploy_EE section of release workflow fails (only seen on ah_configuration but I assume it will fail everywhere). This isn't high priority as the collection will still be released just this deploy_ee section doesn't work.

See https://github.com/redhat-cop/ah_configuration/actions/runs/3891801194/jobs/6642848075

# Issue Type

- Bug Report

**Comment by djdanielsson** [comment]
Oh.... yea... trying to think of the best way to deal with it... I will try and find sometime today to look at it

**Comment by djdanielsson** [comment]
Ok so I am pretty sure the way to fix it is update the [build_EE workflow ](https://github.com/redhat-cop/ansible_collections_tooling/blob/main/.github/workflows/build_ee.yml) workflow to checkout/clone the tooling repo not the repo that is having the release done. Off hand I don't know how to do that and idk when I will get around to figuring it out, if someone else knows off hand how to then we can test that, if not I will keep it on my list to do and get to it when I can.

**Comment by sean-m-sullivan** [comment]
Success, going to make the changes to the other 3 repos so they get the username/pass and this is good. 
https://github.com/redhat-cop/ah_configuration/actions/runs/3907715958

**Comment by sean-m-sullivan** [comment]
This should not be an issue, we had a test with ah_config last night, and ee_utilities new integrated test are successful, so closing.
